version: '3.8'

services:
  mongo:
    container_name: mongodb_demo
    image: mongo:latest
    cap_add:
      - SYS_NICE
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: sapl4db
      MONGO_DB_USERNAME: root
      MONGO_DB_PASSWORD: root
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
