apiVersion: apps/v1
kind: Deployment
metadata:
  name: saplplayground
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saplplayground
  template:
    metadata:
      labels:
        app: saplplayground
    spec:
      containers:
        - name: saplplayground
          image: ghcr.io/heutelbeck/sapl-demo-playground:3.0.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 768Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: saplplayground-balancer
spec:
  selector:
    app: saplplayground
  ports:
    - protocol: TCP
      port: 8080 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
