package io.sapl.demo.generator.example;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ExampleProvider {

    /* ### DEPARTMENTS ### */
    public static final String DEPARTMENT_ANESTHESIOLOGY = "ANESTHESIOLOGY";
    public static final String DEPARTMENT_BOARD = "BOARD";
    public static final String DEPARTMENT_CARDIOLOGY = "CARDIOLOGY";
    public static final String DEPARTMENT_FINANCE = "FINANCE";
    public static final String DEPARTMENT_GYNECOLOGY = "GYNECOLOGY";
    public static final String DEPARTMENT_HUMAN_RESOURCES = "HUMAN_RESOURCES";
    public static final String DEPARTMENT_LABORATORY = "LABORATORY";
    public static final String DEPARTMENT_MANAGEMENT = "MANAGEMENT";
    public static final String DEPARTMENT_NEUROLOGY = "NEUROLOGY";
    public static final String DEPARTMENT_ONCOLOGY = "ONCOLOGY";
    public static final String DEPARTMENT_PHARMACY = "PHARMACY";
    public static final String DEPARTMENT_PURCHASING_SUPPLIES = "PURCHASING_SUPPLIES";
    public static final String DEPARTMENT_RADIOLOGY = "RADIOLOGY";
    public static final String DEPARTMENT_SURGERY = "SURGERY";

    public static final List<String> EXAMPLE_DEPARTMENT_LIST = new ArrayList<>();

    static {
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_ANESTHESIOLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_BOARD);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_CARDIOLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_FINANCE);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_GYNECOLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_HUMAN_RESOURCES);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_LABORATORY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_MANAGEMENT);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_NEUROLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_ONCOLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_PHARMACY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_PURCHASING_SUPPLIES);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_RADIOLOGY);
        EXAMPLE_DEPARTMENT_LIST.add(DEPARTMENT_SURGERY);
    }

    /* ### PER DEPARTMENT ROLES ### */
    public static final String ROLE_ANESTHETIST = "ROLE_ANESTHETIST";
    public static final String ROLE_CARDIOLOGIST = "ROLE_CARDIOLOGIST";
    public static final String ROLE_CENTRAL_BUYER = "ROLE_CENTRAL_BUYER";
    public static final String ROLE_CLINICAL_MANAGER = "ROLE_CLINICAL_MANAGER";
    public static final String ROLE_DIRECTOR = "ROLE_DIRECTOR";
    public static final String ROLE_FINANCE = "ROLE_FINANCE";
    public static final String ROLE_GYNECOLOGIST = "ROLE_GYNECOLOGIST";
    public static final String ROLE_HUMAN_RESOURCES = "ROLE_HUMAN_RESOURCES";
    public static final String ROLE_LAB_TECHNICIAN = "ROLE_LAB_TECHNICIAN";
    public static final String ROLE_NEUROLOGIST = "ROLE_NEUROLOGIST";
    public static final String ROLE_ONCOLOGIST = "ROLE_ONCOLOGIST";
    public static final String ROLE_PHARMACIST = "ROLE_PHARMACIST";
    public static final String ROLE_RADIOLOGIST = "ROLE_RADIOLOGIST";
    public static final String ROLE_SURGEON = "ROLE_SURGEON";

    public static final String ROLE_DOCTOR = "ROLE_DOCTOR";
    public static final String ROLE_INTERN = "ROLE_INTERN";
    public static final String ROLE_NURSE = "ROLE_NURSE";
    public static final String ROLE_PATIENT = "ROLE_PATIENT";
    public static final String ROLE_STUDENT = "ROLE_STUDENT";
    public static final String ROLE_SUPPORT = "ROLE_SUPPORT";
    public static final String ROLE_VISITOR = "ROLE_VISITOR";
    public static final String ROLE_VOLUNTEER = "ROLE_VOLUNTEER";

    public static final List<String> EXAMPLE_GENERAL_ROLE_LIST = new ArrayList<>();

    public static final Map<String, String> DEPARTMENT_ROLE_MAP = new HashMap<>();

    static {
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_ANESTHETIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_CARDIOLOGIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_CENTRAL_BUYER);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_CLINICAL_MANAGER);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_DIRECTOR);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_FINANCE);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_GYNECOLOGIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_HUMAN_RESOURCES);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_LAB_TECHNICIAN);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_NEUROLOGIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_ONCOLOGIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_PHARMACIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_RADIOLOGIST);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_SURGEON);

        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_DOCTOR);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_INTERN);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_NURSE);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_PATIENT);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_STUDENT);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_SUPPORT);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_VISITOR);
        EXAMPLE_GENERAL_ROLE_LIST.add(ROLE_VOLUNTEER);

        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_ANESTHESIOLOGY, ROLE_ANESTHETIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_CARDIOLOGY, ROLE_CARDIOLOGIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_BOARD, ROLE_DIRECTOR);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_FINANCE, ROLE_FINANCE);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_GYNECOLOGY, ROLE_GYNECOLOGIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_HUMAN_RESOURCES, ROLE_HUMAN_RESOURCES);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_LABORATORY, ROLE_LAB_TECHNICIAN);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_MANAGEMENT, ROLE_CLINICAL_MANAGER);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_NEUROLOGY, ROLE_NEUROLOGIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_ONCOLOGY, ROLE_ONCOLOGIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_PHARMACY, ROLE_PHARMACIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_PURCHASING_SUPPLIES, ROLE_CENTRAL_BUYER);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_RADIOLOGY, ROLE_RADIOLOGIST);
        DEPARTMENT_ROLE_MAP.put(DEPARTMENT_SURGERY, ROLE_SURGEON);
    }


    /* ### RESOURCES ### */
    public static final String RESOURCE_DIAGNOSIS = "RESOURCE_DIAGNOSIS";
    public static final String RESOURCE_MEDICATION = "RESOURCE_MEDICATION";
    public static final String RESOURCE_PERSONAL_DETAILS = "RESOURCE_PERSONAL_DETAILS";
    public static final String RESOURCE_ROOM = "RESOURCE_ROOM";
    public static final String RESOURCE_TREATMENT = "RESOURCE_TREATMENT";
    public static final String RESOURCE_INSURANCE = "RESOURCE_INSURANCE";
    public static final String RESOURCE_INVOICES = "RESOURCE_INVOICES";
    public static final String RESOURCE_STAFF = "RESOURCE_STAFF";
    public static final String RESOURCE_DEPARTMENTS = "RESOURCE_DEPARTMENTS";
    public static final String RESOURCE_MEDICAL_DEVICES = "RESOURCE_MEDICAL_DEVICES";
    public static final String RESOURCE_MEDICAL_SUPPLIES = "RESOURCE_MEDICAL_SUPPLIES";

    public static final List<String> EXAMPLE_GENERAL_RESOURCE_LIST = new ArrayList<>();


    static {
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_DIAGNOSIS);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_MEDICATION);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_PERSONAL_DETAILS);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_ROOM);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_TREATMENT);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_INSURANCE);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_INVOICES);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_DEPARTMENTS);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_MEDICAL_DEVICES);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_MEDICAL_SUPPLIES);
        EXAMPLE_GENERAL_RESOURCE_LIST.add(RESOURCE_STAFF);
    }


}
