server:
  port: ${PORT:8080}

spring:
  profiles:
    default: ollama-docker
  threads:
    virtual:
      enabled: true
  ai:
    vectorstore:
      pgvector:
        initialize-schema: true
        dimensions: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW

io:
  sapl:
    pdp:
      embedded:
        print-text-report: true
        print-json-report: false
        print-trace: false
        pretty-print-reports: false

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,io.sapl

logging:
  level:
    io.sapl: info
    org.springframework.ai: DEBUG
    org.atmosphere: warn
    org.springframework.boot.devtools.restart.ChangeableUrls: warn
    org.springframework.security: warn
