server:
  port: ${PORT:8080}

spring:
  profiles:
    default: ollama-docker
  threads:
    virtual:
      enabled: true

vaadin:
  launch-browser: false
  allowed-packages: com.vaadin,org.vaadin,dev.hilla,io.sapl

logging:
  level:
    org.springframework.ai: DEBUG
    org.atmosphere: warn
    org.springframework.boot.devtools.restart.ChangeableUrls: warn
    org.springframework.security: warn
