DROP TABLE IF EXISTS Person;
DROP TABLE IF EXISTS Address;

CREATE TABLE Address (addressId INT PRIMARY KEY, street VARCHAR(255), city VARCHAR(255), zip_code VARCHAR(20));
CREATE TABLE Person (personId INT PRIMARY KEY, firstname VARCHAR(255), lastname VARCHAR(255), age INTEGER, role VARCHAR(255), active BOOLEAN, addressId INT, FOREIGN KEY (addressId) REFERENCES Address(addressId));


insert into Address (addressId, street, city, zip_code) values (50, 'Onsgard', 'Lizhuangzi', null);
insert into Address (addressId, street, city, zip_code) values (51, 'Victoria', 'Lyon', '69907 CEDEX 20');
insert into Address (addressId, street, city, zip_code) values (52, 'Moulton', 'Gayam', null);
insert into Address (addressId, street, city, zip_code) values (53, 'Independence', 'Žďár nad Sázavou Druhy', '592 11');
insert into Address (addressId, street, city, zip_code) values (54, 'Quincy', 'Balagui', '6549');
insert into Address (addressId, street, city, zip_code) values (55, 'Michigan', 'Susiec', '22-672');
insert into Address (addressId, street, city, zip_code) values (56, 'Magdeline', 'Marseille', '13382 CEDEX 13');
insert into Address (addressId, street, city, zip_code) values (57, 'Transport', 'Vila Maior', '4525-485');
insert into Address (addressId, street, city, zip_code) values (58, 'Blue Bill Park', 'Basak', '5317');
insert into Address (addressId, street, city, zip_code) values (59, 'Anhalt', 'Kuala Lumpur', null);
insert into Address (addressId, street, city, zip_code) values (60, 'Hoard', 'Lương Bằng', null);
insert into Address (addressId, street, city, zip_code) values (61, 'Anniversary', 'San Juan', '3611');
insert into Address (addressId, street, city, zip_code) values (62, 'Johnson', 'Starcevica', null);
insert into Address (addressId, street, city, zip_code) values (63, 'Luster', 'Atlanta', '30328');
insert into Address (addressId, street, city, zip_code) values (64, 'Delladonna', 'Kuala Lumpur', null);
insert into Address (addressId, street, city, zip_code) values (65, 'Merry', 'Belo Blato', null);
insert into Address (addressId, street, city, zip_code) values (66, 'Anzinger', 'Lolak', null);
insert into Address (addressId, street, city, zip_code) values (67, 'Saint Paul', 'Jishan', null);
insert into Address (addressId, street, city, zip_code) values (68, 'Debra', 'Buk', '64-320');
insert into Address (addressId, street, city, zip_code) values (69, 'Roxbury', 'Cesvaine', null);
insert into Address (addressId, street, city, zip_code) values (70, 'Dryden', 'La Clotilde', '3701');
insert into Address (addressId, street, city, zip_code) values (71, 'Paget', 'Lionel Town', null);
insert into Address (addressId, street, city, zip_code) values (72, 'Heffernan', 'Alderetes', '4178');
insert into Address (addressId, street, city, zip_code) values (73, 'Bayside', 'Naukšēni', null);
insert into Address (addressId, street, city, zip_code) values (74, 'Roth', 'Youssoufia', null);
insert into Address (addressId, street, city, zip_code) values (75, 'Troy', 'Gayam', null);
insert into Address (addressId, street, city, zip_code) values (76, 'Blackbird', 'Wanghu', null);
insert into Address (addressId, street, city, zip_code) values (77, 'Blackbird', 'Quinta', '4600-652');
insert into Address (addressId, street, city, zip_code) values (78, 'Meadow Ridge', 'Biskamzha', '655735');
insert into Address (addressId, street, city, zip_code) values (79, 'Cody', 'Huaqiao', null);
insert into Address (addressId, street, city, zip_code) values (80, 'Gerald', 'Pampas Chico', null);
insert into Address (addressId, street, city, zip_code) values (81, 'Stuart', 'Anyang', null);
insert into Address (addressId, street, city, zip_code) values (82, 'Fair Oaks', 'Uppsala', '757 54');
insert into Address (addressId, street, city, zip_code) values (83, '7th', 'Braga', '4700-005');
insert into Address (addressId, street, city, zip_code) values (84, 'Sutherland', '‘Izrā', null);
insert into Address (addressId, street, city, zip_code) values (85, 'Ohio', 'Tomteboda', '173 18');
insert into Address (addressId, street, city, zip_code) values (86, 'Mayer', 'Olenyok', '641023');
insert into Address (addressId, street, city, zip_code) values (87, 'Morningstar', 'Hila', null);
insert into Address (addressId, street, city, zip_code) values (88, 'Merry', 'Helie', null);
insert into Address (addressId, street, city, zip_code) values (89, 'Myrtle', 'Tateyama', '999-6732');
insert into Address (addressId, street, city, zip_code) values (90, 'Quincy', 'Idenao', null);
insert into Address (addressId, street, city, zip_code) values (91, 'Beilfuss', 'Chenghuang', null);
insert into Address (addressId, street, city, zip_code) values (92, 'Veith', 'Lakeland', '33811');
insert into Address (addressId, street, city, zip_code) values (93, 'Boyd', 'Quế Sơn', null);
insert into Address (addressId, street, city, zip_code) values (94, 'Monica', 'Zheleznovodsk', '357408');
insert into Address (addressId, street, city, zip_code) values (95, 'Dwight', 'Karangduren Dua', null);
insert into Address (addressId, street, city, zip_code) values (96, 'Sherman', 'Palama', null);
insert into Address (addressId, street, city, zip_code) values (97, 'Oak Valley', 'Obanazawa', '999-4221');
insert into Address (addressId, street, city, zip_code) values (98, 'Cottonwood', 'Itu', '13300-000');
insert into Address (addressId, street, city, zip_code) values (99, 'Daystar', 'Daixi', null);
insert into Address (addressId, street, city, zip_code) values (100, 'Hanson', 'Lingmen', null);

insert into Person (personId, firstname, lastname, age, role, active, addressId) values (1, 'Malinda', 'Perrot', 53, 'ADMIN', true, 100);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (2, 'Emerson', 'Rowat', 82, 'USER', false, 99);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (3, 'Yul', 'Barukh', 79, 'USER', true, 98);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (4, 'Terrel', 'Woodings', 96, 'USER', true, 97);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (5, 'Martino', 'Bartolijn', 33, 'USER', false, 96);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (6, 'Konstantine', 'Hampton', 96, 'USER', false, 95);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (7, 'Cathleen', 'Simms', 25, 'ADMIN', false, 94);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (8, 'Adolphe', 'Streeton', 46, 'USER', true, 93);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (9, 'Alessandro', 'Tomaskov', 64, 'USER', true, 92);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (10, 'Hobie', 'Maddinon', 32, 'USER', false, 91);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (11, 'Franni', 'Mingey', 57, 'ADMIN', false, 90);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (12, 'Giraldo', 'Scade', 83, 'USER', true, 89);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (13, 'Pooh', 'Cocks', 19, 'ADMIN', true, 88);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (14, 'Mario', 'Albinson', 54, 'USER', false, 87);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (15, 'Olav', 'Hoopper', 31, 'USER', true, 86);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (16, 'Tuckie', 'Morfell', 35, 'USER', true,85);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (17, 'Sylas', 'Bickerstasse', 66, 'USER', true,84);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (18, 'Kacey', 'Angell', 94, 'USER', false, 83);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (19, 'Dame', 'Negri', 67, 'USER', true, 82);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (20, 'Perren', 'Durtnall', 75, 'USER', false, 81);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (21, 'Katleen', 'Capstaff', 82, 'ADMIN', true, 80);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (22, 'Candis', 'Souza', 90, 'ADMIN', true, 79);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (23, 'Mac', 'Deetlof', 55, 'USER', false, 78);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (24, 'Tabby', 'Skittreal', 93, 'ADMIN', true, 77);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (25, 'Adriano', 'Tennet', 60, 'USER', false, 76);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (26, 'Cameron', 'Garnham', 39, 'USER', true, 75);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (27, 'Jeri', 'Toppin', 79, 'ADMIN', false, 74);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (28, 'Josselyn', 'Tongs', 34, 'ADMIN', true, 73);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (29, 'Reynolds', 'Buesnel', 55, 'USER', false, 72);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (30, 'Hedwig', 'Berrill', 66, 'ADMIN', true, 71);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (31, 'Karylin', 'Schule', 81, 'ADMIN', false, 70);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (32, 'Thaddeus', 'Machin', 50, 'USER', true, 69);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (33, 'Rhody', 'Vasilic', 72, 'ADMIN', true, 68);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (34, 'Josy', 'Skein', 58, 'ADMIN', true, 67);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (35, 'Rachael', 'Baukham', 57, 'ADMIN', true, 66);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (36, 'Claudianus', 'Courtois', 98, 'USER', false, 65);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (37, 'Imelda', 'Gilkes', 65, 'USER', false, 64);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (38, 'Marcelia', 'Elmer', 24, 'ADMIN', false, 63);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (39, 'Lib', 'Peschka', 89, 'ADMIN', false, 62);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (40, 'Winna', 'Shellshear', 46, 'ADMIN', false, 61);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (41, 'Patty', 'O''Mahoney', 52, 'USER', true, 60);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (42, 'Jerrylee', 'Lukas', 76, 'ADMIN', true, 59);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (43, 'Fielding', 'MacGibbon', 53, 'USER', false, 58);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (44, 'Tuckie', 'Hugett', 29, 'USER', false, 57);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (45, 'Penrod', 'Munehay', 70, 'USER', false, 56);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (46, 'Lexine', 'Blakden', 91, 'ADMIN', true, 55);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (47, 'Petra', 'Shackleford', 97, 'ADMIN', true, 54);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (48, 'Glenn', 'Stennes', 45, 'USER', true, 53);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (49, 'Morry', 'Wolfer', 23, 'USER', false, 52);
insert into Person (personId, firstname, lastname, age, role, active, addressId) values (50, 'Dianemarie', 'Howgill', 69, 'USER', true, 51);
