io.sapl.pdp:
# The following lines show the default configuration and could be omitted.
# pdp-config-type may be RESOURCES (loading policies and configuration from bundles resources) 
# or FILESYSTEM (loading policies and configuration from a folder on the filesystem
  embedded:
    pdp-config-type: RESOURCES
    # defines the path (in resources or filesystem respectively) for the pdp.json file with combining algorithm and variables
    config-path: /policies
    # defines the path (in resources or filesystem respectively) containing .sapl files with policies and policy sets
    policies-path: /policies
# The following options enable or disable different levels of logging for decisions.
#
# print-trace: true|false This is the most fine-grained explanation of a decision made
#                         by the PDP each individual calculation step is documented.
#                         The trace is in JSON format and may become very large.
#                         Recommended only as a last resort for troubleshooting.
    print-trace: false
# print-json-report: true|false This is a JSON report summarizing the applied algorithms
#                               and results of each evaluated policy (set) in the
#                               decision-making process. It includes lists of all errors and values
#                               of policy information point attributes encountered
#                               during the evaluation of each policy (set).
    print-json-report: true
# print-text-report: true|false This will log a human-readable textual report based on the
#                               same data as the 'print-json-report' option generates.
    print-text-report: false
# pretty-print-reports: true|false This option can enable formatting of JSON data while
#                                  printing JSON during reporting and tracing.
#                                  If it is intended to copy&paste JSON from the console-log
#                                  it is recommended to keep this turned off.
    pretty-print-reports: false
    

# The following lines of configuration are for connecting the application to a remote PDP.
# To do so, replace the dependency to sapl-spring-pdp-embedded with sapl-spring-pdp-remote
# The following settings are select that it will connect to a sapl-server-lt you started locally with mvn spring-boot:run
  remote:
    type: http
    host: https://localhost:8443
    # These are the default credentials configured for the sapl-server-lt when running with the 'local' profile
    key: xwuUaRD65G
    secret: 3j_PK71bjy!hN3*xq.xZqveU)t5hKLR_
    # Do not add this parameter in production! This is only for testing with self-signed localhost certificates during development
    ignoreCertificates: true

# The context path and port to use for this demo application
# (http://localhost:8080)
server:
  port: 8080
  servlet.context-path: /

spring:
  # do not show the default spring banner
  main.banner-mode: off
# Set the log level to DEBUG or TRACE to get detailed information about the
# policy engine decision process.
logging.level:
  io.sapl: DEBUG
#logging.level.org.springframework.security.access.vote=TRACE
  org.springframework.security: WARN
