= HowTo: Best Practices to Integrate SAPL with Spring Security Standard Mechanisms
:toc:
:toc-title:
:linkattrs:



***

== Introduction

Many approaches to secure web applications have been developed. Well-known frameworks
bring along built-in components. Here we use https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-documentation/src/asciidoc/sapl-reference.adoc[SAPL] (Structure and Agency Policy Language)
inside a https://projects.spring.io/spring-boot/[Spring Boot] Application with https://maven.apache.org/[Maven] to implement user rights
to webpages and REST services.

== Domain Model

Our domain model is implemented in the submodule https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-domain[sapl-demo-domain]
and kept simple for the sake of clarity. +
We have patients:

```java

public class Patient {

@Id
@GeneratedValue(strategy = GenerationType.AUTO)
int id;

String name;
String diagnosis;
String healthRecordNumber;
String phoneNumber;
String attendingDoctor;
String attendingNurse;
String roomNumber;


public Patient(String name, String diagnosis, String healthRecordNumber, String phoneNumber, String attendingDoctor, String attendingNurse, String roomNumber) {
    this.name = name;
    this.diagnosis = diagnosis;
    this.healthRecordNumber = healthRecordNumber;
    this.phoneNumber = phoneNumber;
    this.attendingDoctor = attendingDoctor;
    this.attendingNurse = attendingNurse;
    this.roomNumber = roomNumber;
}
}

```
There are users:

```java
public class User implements Serializable {

    private static final long serialVersionUID = 1;

    @Id
    String name;

    String password;
    boolean disabled;
    ArrayList<String> functions; // DOCTOR , NURSE , VISITOR, ADMIN

}
```
`VISITOR, DOCTOR , NURSE, ADMIN` characterize `Authorities` in the context of `Spring Security`.



Relations are modeled between patients and users:

```java
public class Relation {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	int id;

	String username;
	int patientid;

	public Relation (String username, int patientid) {
		this.username = username;
		this.patientid = patientid;
	}
}

```

== User Rights

User rights are constantly refined and captured with human readable phrases within SAPL Policies.
Here is a small excerpt of access permissions to `Patient` fields  for  particular authorities:

- `VISITOR` +
can only read phoneNumber and name; is not allowed for  updating and deleting;
- `NURSE` +
can read phoneNumber, name, a blackened  healthRecordNumber; can read diagnosis only if she is attendingNurse;
is allowed for updating name, phoneNumber;
is allowed for updating attendingNurse; is not allowed for deleting;
- `DOCTOR` +
 can read all Patient fields, but only diagnosis if she is attendingDoctor;
 can update all fields, but only diagnosis if she is attendingDoctor; is allowed for deleting Patients;

The following table gives an overview of all current user rights:

.User rights
[frame="topbot",options="header"]
|=============================================================================================================================================================
|User Role| see name|see phone|see HRN   |see diagnosis   |update diagnosis|create patient|update patient    |delete patient|change att. doctor|change att. nurse|see room number    |
|Doctor   |    X    |     X   |   X      |X (only att.doc)|X (only att.doc)|       X      |        X         |      X       |         X        |                 | X (only relatives)|
|Nurse    |    X    |     X   |blacken(1)|X (only att.nur)|                |              |X (name and phone)|              |                  |         X       | X (only relatives)|
|Visitor  |    X    |     X   |          |                |                |              |                  |              |                  |                 | X (only relatives)|
|=============================================================================================================================================================

== Submodule https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-permeval['sapl-demo-permeval']

This submodule  makes extensive use of the Interface PermissionEvaluator from https://projects.spring.io/spring-security/[Spring Security].

=== sapl-spring-boot-starter

Obtaining a decision from SAPL Policies we need a `PolicyDecisionPoint`(`PDP`). A `PDP` as a `bean`  is  available as dependency for
a Spring Boot Starter Project, configured in the submodule https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter]
from project https://github.com/heutelbeck/sapl-policy-engine.
Remote or embedded `PDP` can be integrated into a Spring Boot Project with:

```java
<dependency>
        <groupId>io.sapl</groupId>
        <artifactId>sapl-spring-boot-starter</artifactId>
        <version>1.0.0-SNAPSHOT</version>
</dependency>
```

=== sapl-spring


In conjunction with SAPL requests we need information about an authenticated user, objects of the domain model,
the system environment, HttpServletRequest parameters, the requested URI, et cetera,  and last but not least we need a customized
PermissionEvaluator, the <<SAPLPermissionEvaluator>>.
The submodule https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring[sapl-spring] from https://github.com/heutelbeck/sapl-policy-engine provides these interfaces and classes,
which  can be integrated into a Spring Boot Project with:

```java
<dependency>
        <groupId>io.sapl</groupId>
        <artifactId>sapl-spring</artifactId>
        <version>1.0.0-SNAPSHOT</version>
</dependency>
```

=== Spring Features

General spring features in this submodule are:

* https://projects.spring.io/spring-boot/[Spring Boot]
* Standard SQL database: http://www.h2database.com[H2] (In-Memory), programmable via JPA
* http://hibernate.org/[Hibernate]
* web interfaces (Rest, UI) with Spring MVC
* model classes (Patient, User, Relation), CrudRepositories in JPA
* https://projects.spring.io/spring-security/[Spring Security]
* Thymeleaf

=== Spring Security Features


We refer to the https://projects.spring.io/spring-security/[Spring Security] webpage and
its https://docs.spring.io/spring-security/site/docs/5.0.1.BUILD-SNAPSHOT/reference/htmlsingle/[reference manual].

Successfully implemented features are presented below:

==== Http Security

A loginPage, logoutPage is implemented. There is a secured  REST Service. Each request needs authentication.

Example from a class https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permeval/src/main/java/io/sapl/peembedded/config/SecurityConfig.java[SecurityConfig.java]:


``` java
@Override
protected void configure(HttpSecurity http) throws Exception {
    LOGGER.debug("start configuring...");
    http
            .authorizeRequests()
            .anyRequest().authenticated()
            .and()
            .formLogin()
            .loginPage("/login").permitAll()
            .and()
            .logout().logoutUrl("/logout").logoutSuccessUrl("/login").permitAll()
            .and()
            .httpBasic()
            .and()
            .csrf().disable();
    http.headers().frameOptions().disable();

}
```



==== @Pre and @Post Annotations [[bookmark1]]

`@Pre` and `@Post` annotations are enabled with `@EnableGlobalMethodSecurity(prePostEnabled=true)`  at an instance of   `WebSecurityConfigurerAdapter` .

``` java
@Slf4j
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled=true)
public class SecurityConfig extends WebSecurityConfigurerAdapter {
....
   }
```




==== Permission Evaluator

`hasPermission()` expressions are delegated to an instance of `PermissionEvaluator`.

``` java
@PreAuthorize("hasPermission(#request, #request)")
```


The `PermissionEvaluator` interface is implemented in the <<SAPLPermissionEvaluator>>, which again is enabled  as bean
in the class https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-spring-boot-starter/src/main/java/io/sapl/springboot/starter/PDPAutoConfiguration.java[PDPAutoConfiguration]
from submodule https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter].




=== SAPLPermissionEvaluator
xxx


