= Best Practices to Integrate SAPL with Spring Security Standard Mechanisms
:toc:
:toc-title:
:linkattrs:



***

== Introduction

We want to show how to implement user authorization to applications like webpages and REST services with https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-documentation/src/asciidoc/sapl-reference.adoc[SAPL] (Structure and Agency Policy Language)
inside a https://projects.spring.io/spring-boot/[Spring Boot] Application.

=== Why spring?
Spring(boot) with its subproject https://projects.spring.io/spring-security/[Spring Security] seems to us as a (if not the) leading framework to implement
modern java-based applications. SAPL is developed with no concrete framework in mind to include its features.
One of the targets developing SAPL is to provide interfaces to implement the technology in any kind of modern
java based application. In this project we want to show ways to use it together with springsecurity. 

We tried not to reinvent the wheel and respect as far as possible the opinionated spring view.

Therefore inspecting the framework we found several starting-points to integrate SAPL with springsecurity:

* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/spring-mvc-app[spring-mvc-app] you find two ways to use SAPL.
The direct way of calling the PolicyEnforcementPoint-Bean (e.g. in a MVC-Controller, writing the authorization decision in
the model). And the perhaps a little bit more sophisticated way of using aspects and SAPL-specific annotations.
* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain[sapl-demo-filterchain] we inject a SAPL-specific filter into the springsecurity-Filterchain. The filter protects a classic MVC-controller as well as a ReST-Controller.
The demo also uses the direct way of calling the PolicyEnforcementPoint-Bean.
* In the sub-project https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-reactive[sapl-demo-reactive] we demonstrate different ways of taking advantage from the new reactive API of the Policy Decision Point. Please read the according README.md file of this sub-project.

All these demos make use of SAPL-specific features provided by the project sapl-spring. In particular every project makes use of a spring-fashioned auto-starter that offers default SAPL-functionality in form of beans and the like. The functionality is kept configurable and overridable as possible to support various use cases. 


== Installation

* Prerequisites:
**  Installation of  Java 8 JDK
** Installation of Maven 3
** For IDE user: Installation of your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)
**  For IDE user: Installation of Project Lombok. +
   Some of our modules make extensive use of https://projectlombok.org/download.html. Download lombok.jar run it as a Java application and follow the instructions. If this is not installed and you are working with a Project using Lombok you will end up with a lot of error messages within _Eclipse_, even if the maven build works just fine. +
   For _IntelliJIDEA_ : Install Project https://plugins.jetbrains.com/plugin/6317-lombok-plugin[Lombok Plugin] from the settings or manually.
** For IDE user: Installation of the Spring IDE plugins.

* Clone or download https://github.com/heutelbeck/sapl-demos, or +
import the whole project into your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)  as Maven Project from Version Control.

* Build the project at the root level with `mvn install`.

* Go to sub-projects like +
 https://github.com/heutelbeck/sapl-demos/blob/master/spring-mvc-app[spring-mvc-app], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain[sapl-demo-filterchain] +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-reactive[sapl-demo-reactive] +
 and start the application with `mvn spring-boot:run`. +
  In your favorite IDE  run as SpringBootApp or run the main class of the sub-project.

* default usernames of vistors are: Dominic +
  default usernames of doctors are: Julia, Peter, Alina +
  default usernames of nurses are: Thomas, Brigitte, Janosch, Janina +
  default usernames of admins are: Horst +
  default password of all user is: password


== Getting started
In this section you will find elements of the SAPL Spring Integration which are used in all sub-projects. You also will obtain knowledge about using this API when integrating SAPL into your own Spring Project.
The basic things you have to understand first is how to add the `sapl-spring-boot-starter` to your project and how to use the `PolicyEnforcementPoint`.

=== sapl-spring-boot-starter

The https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] automatically provides all Beans you need to use the SAPL Spring Integration API. It also adds a dependency to the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring[sapl-spring] module, which lets include all features of this API.

Add the following maven dependency to integrate the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] into a Spring Boot Project:

```java
<dependency>
        <groupId>io.sapl</groupId>
        <artifactId>sapl-spring-boot-starter</artifactId>
        <version>2.0.0-SNAPSHOT</version>
</dependency>
```

First of all, the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] adds a `Policy Decision Point` (`PDP`) to your application. You can configure the `PDP` in your `application.properties`. Here is a simple example for the configuration of an embedded PDP:

```java
io.sapl.pdp-type=embedded
io.sapl.pdp-config-type=resources
io.sapl.resources.config-path=/policies
io.sapl.prp-type=resources
io.sapl.resources.policies-path=/policies
```

Furthermore, the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] allows you to use all features that are presented in the demo projects of this repository like the `PolicyEnforcementPoint`, the `@PreEnforce` and `@PostEnforce` annotations and the `PolicyEnforcementFilterPEP`. For more information on these features just have a look at the corresponding demo projects.

=== The PolicyEnforcementPoint

The https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-spring/src/main/java/io/sapl/spring/PolicyEnforcementPoint.java[PolicyEnforcementPoint] receives a SAPL `Authorization Subscription` and sends it to the `PDP`. After receiving the authorization decision, it also cares about the `Obligation` and `Advice` handling.

The `PolicyEnforcementPoint` provides methods to evaluate SAPL authorization decisions. With `enforce` you receive a flux emitting authorization decisions (`PERMIT` or `DENY`). With `filterEnforce` you can get the complete PDP authorization decision. This is useful if you need an element of the authorization decision like for example a blackened resource. Both of these methods can be called with or without `environment`. There is also a variant of `filterEnforce` accepting a multi-subscription and returning a flux emitting authorization decisions to the individual authorization subscriptions of the multi-subscription as soon as they are available. An additional method `filterEnforceAll` also accepts a multi-subscription, but returns a flux emitting multi-decisions containing authorization decisions for all the authorization subscriptions of the multi-subscription. This piece of code shows all options:

```java

@Autowired
PolicyEnforcementPoint pep;

Flux<Decision> decisionFlux = pep.enforce(subject, action, resource);

Flux<Decision> decisionFlux = pep.enforce(subject, action, resource, environment);

Flux<AuthorizationDecision> authzDecisionFlux = pep.filterEnforce(subject, action, resource);

Flux<AuthorizationDecision> authzDecisionFlux = pep.filterEnforce(subject, action, resource, environment);

Flux<IdentifiableAuthorizationDecision> identifiableAuthzDecisionFlux = pep.filterEnforce(multiSubscription);

Flux<MultiAuthorizationDecision> multiAuthzDecisionFlux = pep.filterEnforceAll(multiSubscription);
```

You can call these methods in your code, but the `PolicyEnforcementPoint` is also used by all features presented in this demo repository like the `@PreEnforce` and `@PostEnforce` annotations, the `PolicyEnforcementFilterPEP`, etc.


== Domain Model

All sub-projects  share the same domain model.
We are using terms from the medical field and health care to illustrate how a user (doctor, nurse, visitor, admin) is allowed to get access to patient data.


Our domain model is implemented in the module https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-domain[sapl-demo-domain]
and kept simple for the sake of clarity. +
We have patients:

```java
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Patient {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	String medicalRecordNumber;
	String name;
	String icd11Code;
	String diagnosisText;
	String attendingDoctor;
	String attendingNurse;
	String phoneNumber;
	String roomNumber;

}

```
There are user having a username, password and roles like `VISITOR, DOCTOR , NURSE, ADMIN` characterizing `Authorities` in the context of `Spring Security`.

Relations are modeled between patients and user:

```java
@Data
@Entity
@NoArgsConstructor
@AllArgsConstructor
public class Relation {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	Long id;

	String username;

	Long patientid;

	public Relation(String username, Long patientid) {
		this.username = username;
		this.patientid = patientid;
	}

}

```

== User Rights

User rights are constantly refined and captured with human readable phrases within SAPL Policies.
Here is a small excerpt of access permissions to `Patient` fields for particular authorities:

- `VISITOR` +
can only read phoneNumber and name; is not allowed for updating and deleting;
- `NURSE` +
can read phoneNumber, name, a blackened icd11Code; can read diagnosis only if she is attendingNurse;
is allowed for updating name, phoneNumber;
is allowed for updating attendingNurse; is not allowed for deleting;
- `DOCTOR` +
 can read all Patient fields, but only diagnosis if she is attendingDoctor;
 can update all fields, but only diagnosis if she is attendingDoctor; is allowed for deleting Patients;

The following table gives an overview of all current user rights:

.User rights
[frame="topbot",options="header"]
|=============================================================================================================================================================
|User Role| see name|see phone|see icd11Code|see diagnosis   |update diagnosis|create patient|update patient    |delete patient|change att. doctor|change att. nurse|see room number    |
|Doctor   |    X    |     X   |      X      |X (only att.doc)|X (only att.doc)|       X      |        X         |      X       |         X        |                 | X (only relatives)|
|Nurse    |    X    |     X   |  blacken(1) |X (only att.nur)|                |              |X (name and phone)|              |                  |         X       | X (only relatives)|
|Visitor  |    X    |     X   |             |                |                |              |                  |              |                  |                 | X (only relatives)|
|=============================================================================================================================================================

== Spring Features
Spring features in all sub-projects  are:

* https://projects.spring.io/spring-boot/[Spring Boot]
* Standard SQL database: http://www.h2database.com[H2] (In-Memory), programmable via JPA
* http://hibernate.org/[Hibernate]
* web interfaces (Rest, UI) with Spring MVC
* model classes (Patient, User, Relation), CrudRepositories in JPA
* https://projects.spring.io/spring-security/[Spring Security]
* https://www.thymeleaf.org/[Thymeleaf]

