= Best Practices to Integrate SAPL with Spring Security Standard Mechanisms
:toc:
:toc-title:
:linkattrs:



***

== Introduction

We want to show how to use https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-documentation/src/asciidoc/sapl-reference.adoc[SAPL] (Structure and Agency Policy Language)
inside a https://projects.spring.io/spring-boot/[Spring Boot] Application with https://maven.apache.org/[Maven] to implement user rights
to webpages and REST services. Each of the below-mentioned tutorials represents one specific technique of securing a web application with SAPL.

== Installation

* Prerequisites:
**  Installation of  Java 8 JDK
** Installation of Maven 3
** For IDE user: Installation of your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)
**  For IDE user: Installation of Project Lombok. +
   Some of our modules make extensive use of https://projectlombok.org/download.html. Download lombok.jar run it as a Java application and follow the instructions. If this is not installed and you are working with a Project using Lombok you will end up with a lot of error messages within _Eclipse_, even if the maven build works just fine. +
   For _IntelliJIDEA_ : Install Project https://plugins.jetbrains.com/plugin/6317-lombok-plugin[Lombok Plugin] from the settings or manually.
** For IDE user: Installation of the Spring IDE plugins.

* Clone or download https://github.com/heutelbeck/sapl-demos, or +
import the whole project into your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)  as Maven Project from Version Control.

* Build the project at the root level with `mvn install`.

* Go to  +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-authorizationaspects[sapl-demo-authorizationaspects], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain[sapl-demo-filterchain] +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-jwt[sapl-demo-jwt], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice[sapl-demo-obligation-advice], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permissionevaluator[sapl-demo-permissionevaluator], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-pip[sapl-demo-pip], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-voter[sapl-demo-voter] +
 and start the application with `mvn spring-boot:run`. +
  In your favorite IDE  run as SpringBootApp or run the main class of the submodule.


== Domain Model

All below-mentioned tutorials  share the same domain model.
We are using terms from the medical field and healthcare to illustrate how a user (doctor, nurse, vistor, admin) is allowed to get access to patient data.


Our domain model is implemented in the module https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-domain[sapl-demo-domain]
and kept simple for the sake of clarity. +
We have patients:

```java

public class Patient {

@Id
@GeneratedValue(strategy = GenerationType.AUTO)
int id;

String name;
String diagnosis;
String healthRecordNumber;
String phoneNumber;
String attendingDoctor;
String attendingNurse;
String roomNumber;


public Patient(String name, String diagnosis, String healthRecordNumber, String phoneNumber, String attendingDoctor, String attendingNurse, String roomNumber) {
    this.name = name;
    this.diagnosis = diagnosis;
    this.healthRecordNumber = healthRecordNumber;
    this.phoneNumber = phoneNumber;
    this.attendingDoctor = attendingDoctor;
    this.attendingNurse = attendingNurse;
    this.roomNumber = roomNumber;
}
}

```
There are users:

```java
public class User implements Serializable {

    private static final long serialVersionUID = 1;

    @Id
    String name;

    String password;
    boolean disabled;
    ArrayList<String> functions; // DOCTOR , NURSE , VISITOR, ADMIN

}
```
`VISITOR, DOCTOR , NURSE, ADMIN` characterize `Authorities` in the context of `Spring Security`.



Relations are modeled between patients and users:

```java
public class Relation {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	int id;

	String username;
	int patientid;

	public Relation (String username, int patientid) {
		this.username = username;
		this.patientid = patientid;
	}
}

```

== User Rights

User rights are constantly refined and captured with human readable phrases within SAPL Policies.
Here is a small excerpt of access permissions to `Patient` fields  for  particular authorities:

- `VISITOR` +
can only read phoneNumber and name; is not allowed for  updating and deleting;
- `NURSE` +
can read phoneNumber, name, a blackened  healthRecordNumber; can read diagnosis only if she is attendingNurse;
is allowed for updating name, phoneNumber;
is allowed for updating attendingNurse; is not allowed for deleting;
- `DOCTOR` +
 can read all Patient fields, but only diagnosis if she is attendingDoctor;
 can update all fields, but only diagnosis if she is attendingDoctor; is allowed for deleting Patients;

The following table gives an overview of all current user rights:

.User rights
[frame="topbot",options="header"]
|=============================================================================================================================================================
|User Role| see name|see phone|see HRN   |see diagnosis   |update diagnosis|create patient|update patient    |delete patient|change att. doctor|change att. nurse|see room number    |
|Doctor   |    X    |     X   |   X      |X (only att.doc)|X (only att.doc)|       X      |        X         |      X       |         X        |                 | X (only relatives)|
|Nurse    |    X    |     X   |blacken(1)|X (only att.nur)|                |              |X (name and phone)|              |                  |         X       | X (only relatives)|
|Visitor  |    X    |     X   |          |                |                |              |                  |              |                  |                 | X (only relatives)|
|=============================================================================================================================================================

== Spring Features
General spring features in all tutorials  are:

* https://projects.spring.io/spring-boot/[Spring Boot]
* Standard SQL database: http://www.h2database.com[H2] (In-Memory), programmable via JPA
* http://hibernate.org/[Hibernate]
* web interfaces (Rest, UI) with Spring MVC
* model classes (Patient, User, Relation), CrudRepositories in JPA
* https://projects.spring.io/spring-security/[Spring Security]
* https://www.thymeleaf.org/[Thymeleaf]

== Getting started
In this section you will find elements of the Sapl Spring Integration which are used in all sub projects.

=== The Sapl Mapper
With the Sapl Mapper you can map every class to something you want to use in your Sapl Request. To map a certain class you have to create a `SaplClassMapper`. The class mapper has to override two methods. The method `getMappedClass` just has to return the class which should be mapped. The method `map` does the actual mapping and returns the result of the mapping. Here you can see an example of a class mapper:

```java
public class AuthenticationMapper implements SaplClassMapper {

	@Override
	public Object map(Object objectToMap, SaplRequestElement element) {
		Authentication authentication = (Authentication) objectToMap;
		return new AuthenticationSubject(authentication);
	}

	@Override
	public Class<?> getMappedClass() {
		return Authentication.class;
	}
}

```

If you want to do different mapping for `SUBJECT`, `ACTION`, `RESOURCE` and `ENVIRONMENT` you can check the `SaplRequestElement`, which tells the mapper on which place the Object that should be mapped is in the Sapl Request. In the following example you can see a mapper, that does different mapping for `ACTION` and `RESOURCE`.

```java
public class HttpServletRequestMapper implements SaplClassMapper {

	@Override
	public Object map(Object objectToMap, SaplRequestElement element) {
		
		HttpServletRequest request = (HttpServletRequest) objectToMap;
		
		if(element == (SaplRequestElement.ACTION)) {
			return new HttpAction(request).getMethod();
		}
		
		if(element == (SaplRequestElement.RESOURCE)) {
			return new HttpResource(request).getUri();
		}
		
		return objectToMap;
	}


	@Override
	public Class<?> getMappedClass() {
		return HttpServletRequest.class;
	}

}
```

You can provide all your mappers to your application by registering them to a `SaplMapper` and by returning this `SaplMapper` in a Bean: 

```java
   @Bean
	public SaplMapper getSaplMapper() {
		SaplMapper saplMapper = new SimpleSaplMapper();
		saplMapper.register(new AuthenticationMapper());
		saplMapper.register(new HttpServletRequestMapper());
		saplMapper.register(new PatientMapper());
		return saplMapper;
	}
```

The `SimpleSaplMapper` is an easy option for getting started. If you want more customization, you can create your own SaplMapper by implementing the interface `SaplMapper`.

== Tutorial  https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-authorizationaspects['sapl-demo-authorizationaspects']

https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-authorizationaspects/README.md

== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain['sapl-demo-filterchain']

https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain/README.md

== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-jwt['sapl-demo-jwt']



== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice['sapl-demo-obligation-advice']

https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice/README.md

== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permissionevaluator['sapl-demo-permissionevaluator']
This tutorial makes extensive use of the https://docs.spring.io/spring-security/site/docs/5.0.2.BUILD-SNAPSHOT/reference/htmlsingle/#el-permission-evaluator[PermissionEvaluator Interface]
from https://projects.spring.io/spring-security/[Spring Security]. +
Go to
https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permissionevaluator/README.md .

== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-pip['sapl-demo-pip']

https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-pip/README.md

== Tutorial https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-voter['sapl-demo-voter']

https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-voter/Readme.MD




