= Best Practices to Integrate SAPL with Spring Security Standard Mechanisms
:toc:
:toc-title:
:linkattrs:



***

== Introduction

We want to show how to implement user authorization to applications like webpages and REST services with https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-documentation/src/asciidoc/sapl-reference.adoc[SAPL] (Structure and Agency Policy Language)
inside a https://projects.spring.io/spring-boot/[Spring Boot] Application.

=== Why spring?
Spring(boot) with its subproject https://projects.spring.io/spring-security/[Spring Security] seems to us as a (if not the) leading framework to implement
modern java-based applications. SAPL is developed with no concrete framework in mind to include its features.
One of the targets developing SAPL is to provide interfaces to implement the technology in any kind of modern
java based application. In this project we want to show ways to use it together with springsecurity. 

We tried not to reinvent the wheel and respect as far as possible the opinionated spring view.

Therefore inspecting the framework we found several starting-points to integrate SAPL with springsecurity:

* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-authorizationaspects[sapl-demo-authorizationaspects] you find two ways to use SAPL.
The direct way of calling the SAPLAuthorizer-Bean (e.g. in a MVC-Controller, writing the response in
the model). And the perhaps a little bit more sophisticated way of using aspects and SAPL-specific annotations.
* The sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice[sapl-demo-obligation-advice] is based on the authorizationaspects-project and shows how to use obligation and advice handlers.
* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain[sapl-demo-filterchain] we inject a SAPL-specific filter into the springsecurity-Filterchain. The filter protects a classic MVC-controller as well as a ReST-Controller.
The demo also uses the direct way of calling the SAPLAuthorizer-Bean.
* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-jwt[sapl-demo-jwt] we show how to use JSON Web tokens together with an annotation that uses Sapl Policies.
* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permissionevaluator[sapl-demo-permissionevaluator]
we make  extensive use of the https://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#el-permission-evaluator[PermissionEvaluator Interface] from Spring Security.
* In the sub-project https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-pip[sapl-demo-pip] we show how to use a SAPL-PolicyInformationPoint to gain additional information required by some policies to make an authorization decision.
* In the sub-project https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-voter[sapl-demo-voter] we show how to use a SaplVoter that can be used together with other voters in the `AccessDecisionManager` of Spring Security.

All these demos make use of SAPL-specific features provided by the project sapl-spring. In particular every project makes use of a spring-fashioned auto-starter that offers default SAPL-functionality in form of beans and the like. The functionality is kept configurable and overridable as possible to support various use cases. 


== Installation

* Prerequisites:
**  Installation of  Java 8 JDK
** Installation of Maven 3
** For IDE user: Installation of your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)
**  For IDE user: Installation of Project Lombok. +
   Some of our modules make extensive use of https://projectlombok.org/download.html. Download lombok.jar run it as a Java application and follow the instructions. If this is not installed and you are working with a Project using Lombok you will end up with a lot of error messages within _Eclipse_, even if the maven build works just fine. +
   For _IntelliJIDEA_ : Install Project https://plugins.jetbrains.com/plugin/6317-lombok-plugin[Lombok Plugin] from the settings or manually.
** For IDE user: Installation of the Spring IDE plugins.

* Clone or download https://github.com/heutelbeck/sapl-demos, or +
import the whole project into your favorite IDE (everything works with _Eclipse_, _IntelliJIDEA_)  as Maven Project from Version Control.

* Build the project at the root level with `mvn install`.

* Go to sub-projects like +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-authorizationaspects[sapl-demo-authorizationaspects], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-filterchain[sapl-demo-filterchain] +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-jwt[sapl-demo-jwt], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice[sapl-demo-obligation-advice], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-permissionevaluator[sapl-demo-permissionevaluator], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-pip[sapl-demo-pip], +
 https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-voter[sapl-demo-voter] +
 and start the application with `mvn spring-boot:run`. +
  In your favorite IDE  run as SpringBootApp or run the main class of the sub-project.

* default usernames of vistors  are :   Dominic +
  default usernames of doctors  are :   Julia, Peter, Alina, Horst +
  default usernames of nurses  are : Thomas, Brigitte, Janosch, Janina +
  default password of all user is:  password


== Getting started
In this section you will find elements of the SAPL Spring Integration which are used in all sub-projects. You also will obtain knowledge about using this API when integrating SAPL into your own Spring Project.
The basic things you have to understand first is how to add the `sapl-spring-boot-starter` to your project and how to use the `SAPLAuthorizer` and the `SaplMapper`.

=== sapl-spring-boot-starter

The https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] automatically provides all Beans you need to use the SAPL Spring Integration API. It also adds a dependency to the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring[sapl-spring] module, which lets include all features of this API.

Add the following maven dependency to integrate the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] into a Spring Boot Project:

```java
<dependency>
        <groupId>io.sapl</groupId>
        <artifactId>sapl-spring-boot-starter</artifactId>
        <version>2.0.0-SNAPSHOT</version>
</dependency>
```

First of all, the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] adds a `Policy Decision Point` (`PDP`) to your application. You can configure the `PDP` in your `application.properties`. Here is a simple example for the configuration of an embedded PDP:

```java
pdp.type=EMBEDDED
pdp.embedded.policyPath=classpath:policies
```

Furthermore, the https://github.com/heutelbeck/sapl-policy-engine/tree/master/sapl-spring-boot-starter[sapl-spring-boot-starter] allows you to use all features that are presented in the demo projects of this repository like the `SAPLAuthorizer`, the `@PdpAuthorize` annotation, the `PolicyEnforcementFilter`, the `SAPLPermissionEvaluator` and the `SaplBasedVoter`. For more information on these features just have a look at the corresponding demo projects.

=== The SAPLAuthorizer

The https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-spring/src/main/java/io/sapl/spring/SAPLAuthorizer.java[SAPLAuthorizer] receives `SaplRequest`, does the mapping and sends the request to the `PDP`. After receiving the response, it also cares about the `Obligation` and `Advice` handling. For more information about the mapping, see below. For more information about `Obligation` and `Advice` handling have a look at  https://github.com/heutelbeck/sapl-demos/blob/master/sapl-demo-obligation-advice/README.md[sapl-demo-obligation-advice] .

The `SAPLAuthorizer` provides four methods to evaluate responses. With `authorize` you receive a `boolean` that is true if the decision was `permit` and false if it was `deny`. With `getResponse` you can get the complete PDP response. This is useful if you need an element of the response like for example a blackened resource. Both of this methods can be called with or without `environment`. This piece of code shows all options:

```java

@Autowired
SAPLAuthorizer sapl

sapl.wouldAuthorize(subject, action, resource)

sapl.wouldAuthorize(subject, action, resource, environment)

sapl.authorize(subject, action, resource)

sapl.authorize(subject, action, resource, environment)

sapl.getResponse(subject, action, resource)

sapl.getResponse(subject, action, resource, environment)
```

You can call these methods in your code, but the `SAPLAuthorizer` is also used by all features presented in this demo repository like the `@PdpAuthorize` annotation, the `PolicyEnforcementFilter`, etc.



=== The Sapl Mapper
With the Sapl Mapper you can map every class to something you want to use in your Sapl Request. To map a certain class you have to create a `SaplClassMapper`. The class mapper has to override two methods. The method `getMappedClass` just has to return the class which should be mapped. The method `map` does the actual mapping and returns the result of the mapping. Here you can see an example of a class mapper:

```java
public class AuthenticationMapper implements SaplClassMapper {

	@Override
	public Object map(Object objectToMap, SaplRequestElement element) {
		Authentication authentication = (Authentication) objectToMap;
		return new AuthenticationSubject(authentication);
	}

	@Override
	public Class<?> getMappedClass() {
		return Authentication.class;
	}
}

```

If you want to do different mapping for `SUBJECT`, `ACTION`, `RESOURCE` and `ENVIRONMENT` you can check the `SaplRequestElement`, which tells the mapper on which place the Object that should be mapped is in the Sapl Request. In the following example you can see a mapper, that does different mapping for `ACTION` and `RESOURCE`.

```java
public class HttpServletRequestMapper implements SaplClassMapper {

	@Override
	public Object map(Object objectToMap, SaplRequestElement element) {
		
		HttpServletRequest request = (HttpServletRequest) objectToMap;
		
		if(element == (SaplRequestElement.ACTION)) {
			return new HttpAction(request).getMethod();
		}
		
		if(element == (SaplRequestElement.RESOURCE)) {
			return new HttpResource(request).getUri();
		}
		
		return objectToMap;
	}


	@Override
	public Class<?> getMappedClass() {
		return HttpServletRequest.class;
	}

}
```

You can provide all your mappers to your application by registering them to a `SaplMapper` and by returning this `SaplMapper` in a Bean: 

```java
   @Bean
	public SaplMapper getSaplMapper() {
		SaplMapper saplMapper = new SimpleSaplMapper();
		saplMapper.register(new AuthenticationMapper());
		saplMapper.register(new HttpServletRequestMapper());
		saplMapper.register(new PatientMapper());
		return saplMapper;
	}
```

The https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-spring/src/main/java/io/sapl/spring/marshall/mapper/SimpleSaplMapper.java[SimpleSaplMapper] is an easy option for getting started. If you want more customization, you can create your own SaplMapper by implementing the interface https://github.com/heutelbeck/sapl-policy-engine/blob/master/sapl-spring/src/main/java/io/sapl/spring/marshall/mapper/SaplMapper.java[SaplMapper].



== Domain Model

All sub-projects  share the same domain model.
We are using terms from the medical field and healthcare to illustrate how a user (doctor, nurse, vistor, admin) is allowed to get access to patient data.


Our domain model is implemented in the module https://github.com/heutelbeck/sapl-demos/tree/master/sapl-demo-domain[sapl-demo-domain]
and kept simple for the sake of clarity. +
We have patients:

```java

public class Patient {

@Id
@GeneratedValue(strategy = GenerationType.AUTO)
int id;

String name;
String diagnosis;
String healthRecordNumber;
String phoneNumber;
String attendingDoctor;
String attendingNurse;
String roomNumber;


public Patient(String name, String diagnosis, String healthRecordNumber, String phoneNumber, String attendingDoctor, String attendingNurse, String roomNumber) {
    this.name = name;
    this.diagnosis = diagnosis;
    this.healthRecordNumber = healthRecordNumber;
    this.phoneNumber = phoneNumber;
    this.attendingDoctor = attendingDoctor;
    this.attendingNurse = attendingNurse;
    this.roomNumber = roomNumber;
}
}

```
There are user:

```java
public class User implements Serializable {

    private static final long serialVersionUID = 1;

    @Id
    String name;

    String password;
    boolean disabled;
    ArrayList<String> functions; // DOCTOR , NURSE , VISITOR, ADMIN

}
```
`VISITOR, DOCTOR , NURSE, ADMIN` characterize `Authorities` in the context of `Spring Security`.



Relations are modeled between patients and user:

```java
public class Relation {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	int id;

	String username;
	int patientid;

	public Relation (String username, int patientid) {
		this.username = username;
		this.patientid = patientid;
	}
}

```

== User Rights

User rights are constantly refined and captured with human readable phrases within SAPL Policies.
Here is a small excerpt of access permissions to `Patient` fields  for  particular authorities:

- `VISITOR` +
can only read phoneNumber and name; is not allowed for  updating and deleting;
- `NURSE` +
can read phoneNumber, name, a blackened  healthRecordNumber; can read diagnosis only if she is attendingNurse;
is allowed for updating name, phoneNumber;
is allowed for updating attendingNurse; is not allowed for deleting;
- `DOCTOR` +
 can read all Patient fields, but only diagnosis if she is attendingDoctor;
 can update all fields, but only diagnosis if she is attendingDoctor; is allowed for deleting Patients;

The following table gives an overview of all current user rights:

.User rights
[frame="topbot",options="header"]
|=============================================================================================================================================================
|User Role| see name|see phone|see HRN   |see diagnosis   |update diagnosis|create patient|update patient    |delete patient|change att. doctor|change att. nurse|see room number    |
|Doctor   |    X    |     X   |   X      |X (only att.doc)|X (only att.doc)|       X      |        X         |      X       |         X        |                 | X (only relatives)|
|Nurse    |    X    |     X   |blacken(1)|X (only att.nur)|                |              |X (name and phone)|              |                  |         X       | X (only relatives)|
|Visitor  |    X    |     X   |          |                |                |              |                  |              |                  |                 | X (only relatives)|
|=============================================================================================================================================================

== Spring Features
Spring features in all sub-projects  are:

* https://projects.spring.io/spring-boot/[Spring Boot]
* Standard SQL database: http://www.h2database.com[H2] (In-Memory), programmable via JPA
* http://hibernate.org/[Hibernate]
* web interfaces (Rest, UI) with Spring MVC
* model classes (Patient, User, Relation), CrudRepositories in JPA
* https://projects.spring.io/spring-security/[Spring Security]
* https://www.thymeleaf.org/[Thymeleaf]

